version: '3.4'
services:
  openvino-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: openvino-dev
    image: openvino-dev
    stdin_open: true
    tty: true
    command: bash

  openvino-runtime:
    build:
      context: .
      dockerfile: Dockerfile
      target: openvino-runtime
    image: openvino-runtime
    stdin_open: true
    tty: true
    command: bash

  sampleapp-dev:
    build:
      context: ./sample-app
      dockerfile: Dockerfile
      target: sampleapp-dev
    image: sampleapp-dev
    stdin_open: true
    tty: true
    command: bash

  sampleapp-runtime:
    build:
      context: ./sample-app
      dockerfile: Dockerfile
      target: sampleapp-runtime
    image: sampleapp-runtime
    stdin_open: true
    tty: true
    command: bash